### ISSUE TITLE
linker error in gui/controls/bitmapcombobox.cpp

### ISSUE THREAD

**Issue by abma** [springlobby/springlobby#690]
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x890): undefined reference to `non-virtual thunk to wxComboCtrlBase::WriteText(wxString const&)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x8b0): undefined reference to `non-virtual thunk to wxComboCtrlBase::Replace(long, long, wxString const&)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x8b8): undefined reference to `non-virtual thunk to wxComboCtrlBase::Remove(long, long)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x8c8): undefined reference to `non-virtual thunk to wxComboCtrlBase::Copy()'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x8d0): undefined reference to `non-virtual thunk to wxComboCtrlBase::Cut()'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x8d8): undefined reference to `non-virtual thunk to wxComboCtrlBase::Paste()'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x8f8): undefined reference to `non-virtual thunk to wxComboCtrlBase::Undo()'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x900): undefined reference to `non-virtual thunk to wxComboCtrlBase::Redo()'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x908): undefined reference to `non-virtual thunk to wxComboCtrlBase::CanUndo() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x910): undefined reference to `non-virtual thunk to wxComboCtrlBase::CanRedo() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x918): undefined reference to `non-virtual thunk to wxComboCtrlBase::SetInsertionPoint(long)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x928): undefined reference to `non-virtual thunk to wxComboCtrlBase::GetInsertionPoint() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x930): undefined reference to `non-virtual thunk to wxComboCtrlBase::GetLastPosition() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x950): undefined reference to `non-virtual thunk to wxOwnerDrawnComboBox::GetSelection(long*, long*) const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x960): undefined reference to `non-virtual thunk to wxComboCtrlBase::IsEditable() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x968): undefined reference to `non-virtual thunk to wxComboCtrlBase::SetEditable(bool)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x978): undefined reference to `non-virtual thunk to wxComboCtrlBase::SetHint(wxString const&)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x980): undefined reference to `non-virtual thunk to wxComboCtrlBase::GetHint() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x988): undefined reference to `non-virtual thunk to wxComboCtrlBase::DoSetValue(wxString const&, int)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x990): undefined reference to `non-virtual thunk to wxComboCtrlBase::DoGetValue() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x9a0): undefined reference to `non-virtual thunk to wxComboCtrlBase::DoSetMargins(wxPoint const&)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0x9a8): undefined reference to `non-virtual thunk to wxComboCtrlBase::DoGetMargins() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0xa08): undefined reference to `non-virtual thunk to wxOwnerDrawnComboBox::GetCount() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0xa10): undefined reference to `non-virtual thunk to wxOwnerDrawnComboBox::GetString(unsigned int) const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0xa18): undefined reference to `non-virtual thunk to wxOwnerDrawnComboBox::SetString(unsigned int, wxString const&)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0xa20): undefined reference to `non-virtual thunk to wxOwnerDrawnComboBox::FindString(wxString const&, bool) const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0xa30): undefined reference to `non-virtual thunk to wxOwnerDrawnComboBox::GetSelection() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0xa58): undefined reference to `non-virtual thunk to wxOwnerDrawnComboBox::DoInsertItems(wxArrayStringsAdapter const&, unsigned int, void**, wxClientDataType)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0xa68): undefined reference to `non-virtual thunk to wxOwnerDrawnComboBox::DoSetItemClientData(unsigned int, void*)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0xa70): undefined reference to `non-virtual thunk to wxOwnerDrawnComboBox::DoGetItemClientData(unsigned int) const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0xa78): undefined reference to `non-virtual thunk to wxOwnerDrawnComboBox::DoClear()'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTVN3GUI8Controls14BitmapComboBoxE[_ZTVN3GUI8Controls14BitmapComboBoxE]+0xa80): undefined reference to `non-virtual thunk to wxOwnerDrawnComboBox::DoDeleteOneItem(unsigned int)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x7f0): undefined reference to `non-virtual thunk to wxComboCtrlBase::WriteText(wxString const&)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x810): undefined reference to `non-virtual thunk to wxComboCtrlBase::Replace(long, long, wxString const&)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x818): undefined reference to `non-virtual thunk to wxComboCtrlBase::Remove(long, long)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x828): undefined reference to `non-virtual thunk to wxComboCtrlBase::Copy()'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x830): undefined reference to `non-virtual thunk to wxComboCtrlBase::Cut()'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x838): undefined reference to `non-virtual thunk to wxComboCtrlBase::Paste()'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x858): undefined reference to `non-virtual thunk to wxComboCtrlBase::Undo()'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x860): undefined reference to `non-virtual thunk to wxComboCtrlBase::Redo()'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x868): undefined reference to `non-virtual thunk to wxComboCtrlBase::CanUndo() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x870): undefined reference to `non-virtual thunk to wxComboCtrlBase::CanRedo() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x878): undefined reference to `non-virtual thunk to wxComboCtrlBase::SetInsertionPoint(long)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x888): undefined reference to `non-virtual thunk to wxComboCtrlBase::GetInsertionPoint() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x890): undefined reference to `non-virtual thunk to wxComboCtrlBase::GetLastPosition() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x898): undefined reference to `non-virtual thunk to wxComboCtrlBase::SetSelection(long, long)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x8b0): undefined reference to `non-virtual thunk to wxComboCtrlBase::GetSelection(long*, long*) const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x8c0): undefined reference to `non-virtual thunk to wxComboCtrlBase::IsEditable() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x8c8): undefined reference to `non-virtual thunk to wxComboCtrlBase::SetEditable(bool)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x8d8): undefined reference to `non-virtual thunk to wxComboCtrlBase::SetHint(wxString const&)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x8e0): undefined reference to `non-virtual thunk to wxComboCtrlBase::GetHint() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x8e8): undefined reference to `non-virtual thunk to wxComboCtrlBase::DoSetValue(wxString const&, int)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x8f0): undefined reference to `non-virtual thunk to wxComboCtrlBase::DoGetValue() const'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x900): undefined reference to `non-virtual thunk to wxComboCtrlBase::DoSetMargins(wxPoint const&)'
src/CMakeFiles/springlobby.dir/gui/controls/bitmapcombobox.cpp.o:(.rodata._ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE[_ZTV17wxWindowWithItemsI11wxComboCtrl15wxItemContainerE]+0x908): undefined reference to `non-virtual thunk to wxComboCtrlBase::DoGetMargins() const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x828): undefined reference to `non-virtual thunk to wxTextCtrl::GetLineLength(long) const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x830): undefined reference to `non-virtual thunk to wxTextCtrl::GetLineText(long) const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x838): undefined reference to `non-virtual thunk to wxTextCtrl::GetNumberOfLines() const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x840): undefined reference to `non-virtual thunk to wxTextCtrl::IsModified() const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x848): undefined reference to `non-virtual thunk to wxTextCtrl::MarkDirty()'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x850): undefined reference to `non-virtual thunk to wxTextCtrl::DiscardEdits()'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x858): undefined reference to `non-virtual thunk to wxTextCtrl::SetStyle(long, long, wxTextAttr const&)'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x860): undefined reference to `non-virtual thunk to wxTextCtrl::GetStyle(long, wxTextAttr&)'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x868): undefined reference to `non-virtual thunk to wxTextCtrlBase::SetDefaultStyle(wxTextAttr const&)'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x878): undefined reference to `non-virtual thunk to wxTextCtrl::XYToPosition(long, long) const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x880): undefined reference to `non-virtual thunk to wxTextCtrl::PositionToXY(long, long*, long*) const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x888): undefined reference to `non-virtual thunk to wxTextCtrl::ShowPosition(long)'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x890): undefined reference to `non-virtual thunk to wxTextCtrl::HitTest(wxPoint const&, long*) const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x8a0): undefined reference to `non-virtual thunk to wxTextCtrl::GetValue() const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x8c8): undefined reference to `non-virtual thunk to wxTextCtrl::DoPositionToCoords(long) const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x900): undefined reference to `non-virtual thunk to wxTextCtrl::WriteText(wxString const&)'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x910): undefined reference to `non-virtual thunk to wxTextCtrl::GetValue() const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x928): undefined reference to `non-virtual thunk to wxTextCtrl::Remove(long, long)'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x938): undefined reference to `non-virtual thunk to wxTextCtrl::Copy()'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x940): undefined reference to `non-virtual thunk to wxTextCtrl::Cut()'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x948): undefined reference to `non-virtual thunk to wxTextCtrl::Paste()'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x988): undefined reference to `non-virtual thunk to wxTextCtrl::SetInsertionPoint(long)'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x998): undefined reference to `non-virtual thunk to wxTextCtrl::GetInsertionPoint() const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x9a0): undefined reference to `non-virtual thunk to wxTextCtrl::GetLastPosition() const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x9a8): undefined reference to `non-virtual thunk to wxTextCtrl::SetSelection(long, long)'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x9c0): undefined reference to `non-virtual thunk to wxTextCtrl::GetSelection(long*, long*) const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x9d0): undefined reference to `non-virtual thunk to wxTextCtrl::IsEditable() const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x9d8): undefined reference to `non-virtual thunk to wxTextCtrl::SetEditable(bool)'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x9e8): undefined reference to `non-virtual thunk to wxTextCtrlBase::SetHint(wxString const&)'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0x9f8): undefined reference to `non-virtual thunk to wxTextCtrl::DoSetValue(wxString const&, int)'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0xa38): undefined reference to `non-virtual thunk to wxTextCtrl::EnableTextChangedEvents(bool)'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0xa40): undefined reference to `non-virtual thunk to wxTextCtrl::GTKIMFilterKeypress(_GdkEventKey*) const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0xa48): undefined reference to `non-virtual thunk to wxTextCtrl::GetEditable() const'
src/CMakeFiles/springlobby.dir/gui/wxtextctrlhist.cpp.o:(.rodata._ZTV14wxTextCtrlHist[_ZTV14wxTextCtrlHist]+0xa50): undefined reference to `non-virtual thunk to wxTextCtrl::GetEntry() const'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by abma** [comment]
no clue, after a clean rebuild it worked :-|

sorry

**Comment by abma** [comment]
i got this error after upgrading from ubuntu 15.10 to 16.04
